let authToken=null,stockSession=null,userProfile=null;
const $=id=>document.getElementById(id);
const api=async(path,options={})=>{const headers=new Headers(options.headers||{});if(authToken)headers.set('Authorization',`Bearer ${authToken}`);const r=await fetch(path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`HTTP ${r.status}`);return d};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(`page-${page}`).classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='entry'&&stockSession)loadResume();}
function setLogin(on){$('loginView').classList.toggle('hidden',!on);$('appView').classList.toggle('hidden',on);}
function msg(id,text,type=''){const e=$(id);e.className=`upload-message ${type}`;e.textContent=text;}
async function loadStores(){try{const d=await fetch('/auth/stores').then(r=>r.json());const s=$('storeSelect');s.innerHTML='<option value="">Pilih toko...</option>'+d.stores.map(x=>`<option value="${esc(x.storeName)}">${esc(x.storeCode)} — ${esc(x.storeName)}</option>`).join('');}catch(e){$('loginError').textContent='Daftar toko tidak dapat dimuat.';}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('loginBtn');btn.disabled=true;btn.textContent='CHECKING...';$('loginError').textContent='';try{const d=await api('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storeName:$('storeSelect').value})});authToken=d.token;userProfile=d;localStorage.setItem('mst_token',authToken);localStorage.setItem('mst_profile',JSON.stringify(d));setLogin(false);await resume();}catch(err){$('loginError').textContent=err.message||'Login gagal.';}finally{btn.disabled=false;btn.textContent='LOGIN';}});
$('logoutBtn').onclick=()=>{authToken=null;stockSession=null;localStorage.removeItem('mst_token');localStorage.removeItem('mst_profile');setLogin(true);go('home');};
$('menuToggle').onclick=()=>{$('sidebar').classList.toggle('collapsed');};
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)go(b.dataset.page);});
async function resume(){try{const d=await api('/sessions/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});stockSession=d;userProfile={...(userProfile||{}),...d};renderProfile();go('home');await loadResume();}catch(e){$('loginError').textContent=e.message;authToken=null;localStorage.removeItem('mst_token');setLogin(true);}}
function renderProfile(){const store=userProfile?.storeName||'—',code=userProfile?.storeCode||'—';['topStore','homeStore','entryStore','storeName','prepareBy','userPosting'].forEach(id=>$(id).textContent=store);$('storeCode').textContent=code;$('userInfo').textContent=`STORE: ${code} — ${store}`;$('sessionCode').textContent=stockSession?.sessionCode||'—';$('summarySession').textContent=stockSession?.sessionCode||'—';$('homeSession').textContent=stockSession?.sessionCode||'—';$('docDate').textContent=stockSession?.startDate||new Date().toLocaleDateString('id-ID');}
async function loadResume(){if(!stockSession)return;try{const d=await api(`/sessions/resume/${stockSession.storeId}`);$('summaryLines').textContent=d.totalLines??0;$('summaryCounted').textContent=d.countedLines??0;$('summaryProgress').textContent=(d.totalLines?Math.round(d.countedLines/d.totalLines*100):0)+'%';$('homeLines').textContent=d.totalLines??0;$('homeCounted').textContent=d.countedLines??0;$('homeProgress').textContent=(d.totalLines?Math.round(d.countedLines/d.totalLines*100):0)+'%';renderProfile();}catch(e){if(e.message!=='NO_ACTIVE_SESSION')console.warn(e);}}
async function upload(type){const file=$(type==='system'?'systemFile':'itemizeFile').files[0],btn=$(type==='system'?'systemUploadBtn':'itemizeUploadBtn'),box=type==='system'?'systemProgress':'itemizeProgress';if(!file){msg(box,'Pilih file terlebih dahulu.','error');return}btn.disabled=true;btn.textContent='UPLOADING...';msg(box,'Uploading dan memproses data...','loading');try{const fd=new FormData();fd.append('file',file);const endpoint=type==='system'?`/sessions/${stockSession.id}/system-db`:`/sessions/${stockSession.id}/itemize`;const d=await api(endpoint,{method:'POST',body:fd});msg(box,`✓ Berhasil: ${d.message||'data tersimpan.'}`,'success');await loadResume();}catch(e){msg(box,`✕ ${e.message}`,'error');}finally{btn.disabled=false;btn.textContent='UPLOAD';}}
$('systemUploadBtn').onclick=()=>upload('system');$('itemizeUploadBtn').onclick=()=>upload('itemize');
$('openRackBtn').onclick=async()=>{const rack=$('rackInput').value.trim();if(!rack)return;$('openRackBtn').disabled=true;try{const d=await api(`/sessions/${stockSession.id}/racks/${encodeURIComponent(rack)}`);$('rackTitle').textContent=d.rackNumber||rack;renderItems(d.items||[]);$('entryMessage').textContent=`${d.items?.length||0} item ditampilkan.`;}catch(e){$('entryMessage').textContent=e.message;}finally{$('openRackBtn').disabled=false;}};
function renderItems(items){const box=$('items');box.innerHTML='';items.forEach((item,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td><strong>${esc(item.sku)}</strong></td><td>${esc(item.barcode||'-')}</td><td>${esc(item.description||'-')}</td><td class="num">${esc(item.systemQty??'-')}</td><td><input class="qty-input" inputmode="decimal" value="${esc(item.physicalQty??'')}" placeholder="Count" data-id="${esc(item.id)}"></td><td class="num">${esc(item.varianceQty??'-')}</td><td><span class="status-chip">${esc(item.status||'—')}</span></td>`;tr.querySelector('input').addEventListener('change',saveQty);box.appendChild(tr);});}
async function saveQty(e){const input=e.target,raw=input.value.trim();if(raw===''){input.focus();return}const n=Number(raw);if(!Number.isFinite(n)||n<0){$('entryMessage').textContent='Physical Qty harus angka >= 0.';input.focus();return}input.disabled=true;try{await api(`/items/${input.dataset.id}/physical-qty`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({physicalQty:n})});input.classList.add('saved');$('entryMessage').textContent='✓ Physical Qty tersimpan.';await loadResume();}catch(err){$('entryMessage').textContent=err.message;}finally{input.disabled=false;}}
$('finalizeBtn').onclick=async()=>{if(!stockSession)return;if(!confirm('Finalize session? Setelah final, Physical Qty tidak dapat diubah.'))return;$('finalizeBtn').disabled=true;$('entryMessage').textContent='Finalizing...';try{const d=await api(`/sessions/${stockSession.id}/finalize`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});$('entryMessage').textContent=`✓ Session finalized · Accuracy ${d.accuracy??'-'}%`;stockSession=null;}catch(e){$('entryMessage').textContent=e.message;}finally{$('finalizeBtn').disabled=false;}};
async function boot(){const saved=localStorage.getItem('mst_token');if(saved){authToken=saved;try{userProfile=JSON.parse(localStorage.getItem('mst_profile')||'{}');setLogin(false);await resume();return}catch{authToken=null;localStorage.removeItem('mst_token');localStorage.removeItem('mst_profile');}}setLogin(true);await loadStores();}
boot();
