/* Midnorth Backend System - browser UI */
let supabaseClient=null;let authSession=null;let stockSession=null;let userProfile=null;
const $=id=>document.getElementById(id);
const api=async(path,options={})=>{const headers=new Headers(options.headers||{});if(authSession?.access_token)headers.set('Authorization',`Bearer ${authSession.access_token}`);const res=await fetch(path,{...options,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||data.error||`HTTP ${res.status}`);return data};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function showLogin(on){$('loginView').classList.toggle('hidden',!on);$('appView').classList.toggle('hidden',on)}
function message(id,text,type=''){const el=$(id);el.className=`progress-area ${type}`;el.textContent=text}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(`page-${page}`).classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='entry'&&stockSession)loadResume()}
async function boot(){try{const cfg=await fetch('/config').then(r=>r.json());if(!cfg.supabaseUrl||!cfg.supabaseAnonKey)throw new Error('Konfigurasi Supabase belum tersedia.');supabaseClient=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);const s=await supabaseClient.auth.getSession();authSession=s.data.session;showLogin(!authSession);if(authSession)await resume();supabaseClient.auth.onAuthStateChange((_e,sess)=>{authSession=sess;showLogin(!sess);if(sess)resume().catch(e=>showLoginError(e));});}catch(e){showLoginError(e)}}
function showLoginError(e){$('loginError').textContent=e?.message||String(e)}
async function resume(){const d=await api('/sessions/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});stockSession=d;userProfile=d.user||d.profile||{};const storeName=d.storeName||d.store_name||d.userStoreName||d.storeId||'—';const storeCode=d.storeCode||d.store_code||d.storeId||'—';$('topStore').textContent=storeName;$('userInfo').textContent=`${authSession?.user?.email||''} · ${storeName}`;$('sessionCode').textContent=d.sessionCode||'—';$('summarySession').textContent=d.sessionCode||'—';$('storeCode').textContent=storeCode;$('storeName').textContent=storeName;$('prepareBy').textContent=storeName;$('userPosting').textContent=storeName;$('docDate').textContent=new Date().toLocaleDateString('id-ID');$('homeStatus').textContent=`Active session ${d.sessionCode||''} · ${d.status||'IN_PROGRESS'}`;if(d.lastActiveRack)$('rackInput').value=d.lastActiveRack;await loadResume();}
async function loadResume(){if(!stockSession)return;try{const d=await api(`/sessions/resume/${encodeURIComponent(stockSession.storeId)}`);$('summaryLines').textContent=d.totalLines??0;$('summaryCounted').textContent=d.countedLines??0;const pct=d.totalLines?Math.round((d.countedLines/d.totalLines)*100):0;$('summaryProgress').textContent=`${pct}%`;}catch(_){}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{const {error}=await supabaseClient.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;}catch(err){showLoginError(err)}});
$('logoutBtn').onclick=()=>supabaseClient.auth.signOut();
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
$('systemUploadBtn').onclick=async()=>{try{const f=$('systemFile').files[0];if(!f)throw new Error('Pilih file System Database terlebih dahulu.');message('systemProgress','Uploading & processing System Database…','loading');$('systemUploadBtn').disabled=true;const fd=new FormData();fd.append('file',f);const d=await api(`/sessions/${stockSession.id}/system-db`,{method:'POST',body:fd});message('systemProgress',`✓ Upload berhasil · ${d.inserted??d.rowCount??0} rows diproses.`,'success');await resume()}catch(e){message('systemProgress',`✕ ${e.message}`,'error')}finally{$('systemUploadBtn').disabled=false}};
$('itemizeUploadBtn').onclick=async()=>{try{const f=$('itemizeFile').files[0];if(!f)throw new Error('Pilih file Itemize / Scan Result terlebih dahulu.');message('itemizeProgress','Uploading & processing Itemize…','loading');$('itemizeUploadBtn').disabled=true;const fd=new FormData();fd.append('file',f);const d=await api(`/sessions/${stockSession.id}/itemize`,{method:'POST',body:fd});message('itemizeProgress',`✓ Upload berhasil · +${d.inserted||0} baru · ${d.existing||0} existing · ${d.unknownSku||0} unknown · ${d.wrongRack||0} wrong rack.`,'success');await resume()}catch(e){message('itemizeProgress',`✕ ${e.message}`,'error')}finally{$('itemizeUploadBtn').disabled=false}};
$('openRackBtn').onclick=()=>openRack().catch(e=>{$('entryMessage').textContent=e.message});
async function openRack(){if(!stockSession)await resume();const rack=$('rackInput').value.trim();if(!rack)throw new Error('Isi Rack Number terlebih dahulu.');$('openRackBtn').disabled=true;$('entryMessage').textContent='Loading rack…';try{const d=await api(`/sessions/${stockSession.id}/racks/${encodeURIComponent(rack)}/open`,{method:'POST'});$('rackTitle').textContent=`${rack} · ${d.items.length} lines`;$('entryMessage').textContent=`${d.items.length} item loaded`;$('items').innerHTML='';renderItems(d.items)}finally{$('openRackBtn').disabled=false}}
function renderItems(items){const box=$('items');if(!items.length){box.innerHTML='<tr><td colspan="8">Belum ada item pada rack ini.</td></tr>';return}items.forEach((item,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td><strong>${esc(item.sku)}</strong></td><td>${esc(item.barcode||'-')}</td><td>${esc(item.description||'-')}</td><td style="text-align:right">${esc(item.systemQty??'-')}</td><td><input class="qty-input" inputmode="decimal" value="${item.physicalQty??''}" placeholder="Count" data-id="${esc(item.id)}" /></td><td style="text-align:right">${esc(item.varianceQty??'-')}</td><td>${esc(item.status||'—')}</td>`;tr.querySelector('input').addEventListener('change',e=>saveQty(e.target));box.appendChild(tr)})}
async function saveQty(input){const raw=input.value.trim();if(raw===''){input.focus();return}const n=Number(raw);if(!Number.isFinite(n)||n<0){$('entryMessage').textContent='Physical Qty harus angka >= 0.';input.focus();return}input.disabled=true;try{await api(`/items/${input.dataset.id}/physical-qty`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({physicalQty:n})});input.classList.add('saved');$('entryMessage').textContent='Physical Qty tersimpan.';await loadResume();}catch(e){$('entryMessage').textContent=e.message}finally{input.disabled=false}}
$('finalizeBtn').onclick=async()=>{if(!stockSession)return;if(!confirm('Finalize session? Setelah final, user toko tidak dapat mengubah Physical Qty.'))return;$('finalizeBtn').disabled=true;$('entryMessage').textContent='Finalizing…';try{const d=await api(`/sessions/${stockSession.id}/finalize`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});$('entryMessage').textContent=`Session finalized · Accuracy ${d.accuracy??'-'}%`;$('prepStatus').textContent='Finalized';await resume()}catch(e){$('entryMessage').textContent=e.message}finally{$('finalizeBtn').disabled=false}};
boot();
